### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by so1ve** [disrupted/dprint-plugin-css#13]
Hi, thanks for your awesome plugin!
I am making a eslint plugin to integrate dprint into eslint. The dprint plugins must be published on npm.
Can you publish this package on npm (like @dprint/json)? Thanks a lot!

**Comment by disrupted** [comment]
Hi, thanks for your kind words. I am open to the idea of publishing an NPM package. Would you be willing to send a PR for it? I'd imagine the CI workflow could be based on the example you linked. Unfortunately I don't have the resources to spend a time on this at the moment, but I would be happy to review a contribution.

**Comment by so1ve** [comment]
Sure, I'd love to!
However, I'm not familiar to rust (and napi) so it may take a few times...

**Comment by so1ve** [comment]
Done via #16
