### ISSUE TITLE
calc() with var()s and division is rewritten incorrectly

### ISSUE THREAD

**Issue by myobie** [disrupted/dprint-plugin-css#9]
Amazingly a line like `--width2: calc(var(--a) / var(--b));` will be rewritten as `--width2: calc(var(--a) \ var(--b));` (the / is changed to \).

Here is a failing test case:

```diff
diff --git a/tests/specs/value/calc.txt b/tests/specs/value/calc.txt
index 2ee24c8..f19c448 100644
--- a/tests/specs/value/calc.txt
+++ b/tests/specs/value/calc.txt
@@ -5,6 +5,7 @@
 
 div {
   --width: calc(10% + 30px);
+  --width2: calc(var(--a) / var(--b));
 
   width: calc(0px);
   line-height: calc(0);
@@ -22,6 +23,7 @@ div {
 
 div {
     --width: calc(10% + 30px);
+    --width2: calc(var(--a) / var(--b));
     width: calc(0px);
     line-height: calc(0);
     line-height: calc(2 + 3 * 4);
```

I can try to help come up with more test cases from my codebase (we apparently have a lot of combinations of different css features 😆) later in the week if that would help.

**Comment by disrupted** [comment]
Haha, this is quite an odd bug and my bad for misinterpreting some of the token types. This has been fixed in #8 and will be in the next release.

**Comment by disrupted** [comment]
If you run into any other bugs or unexpected behavior, please don't hesitate to open more issues. It really helps to get these ironed out quickly! I actually rarely write CSS these days, so to me it's helpful if people run this against large codebases.

**Comment by disrupted** [comment]
0.2.2 is released
